### ISSUE TITLE
make 'gh-pages' the default branch and keep it up to date

### ISSUE THREAD

**Issue by dannysepler** [CodeforSouth/MDBudgetviz#25]
The website is hosted on the gh-pages branch so that's the one that should be staying updated. Great to see you all keeping this project alive!

**Comment by ErnieAtLYD** [comment]
Hey @CristinaSolana, I'm gonna do this, but I won't delete the `master` branch since I think we're still merging Matt's branch.

**Comment by CristinaSolana** [comment]
@ErnieAtLYD, Please read the email I sent before doing this. I already addressed the issue there.
